CREATE ROLE professores NOCREATEDB  NOCREATEROLE INHERIT NOLOGIN NOBYPASSRLS CONNECTION LIMIT 10;
ALTER ROLE professores PASSWORD '1234';
-- CREATE ROLE daniel LOGIN PASSWORD '1234'
DROP ROLE daniel;
-- CREATE  ROLE daniel LOGIN PASSWORD '1234' IN ROLE professores;
-- CREATE  ROLE daniel LOGIN PASSWORD '1234' ROLE professores;

CREATE TABLE teste (nome varchar);
GRANT ALL ON TABLE teste TO professores;
CREATE  ROLE daniel LOGIN PASSWORD '1234' IN ROLE professores; 

REVOKE professores FROM daniel;