CREATE ROLE geral
  NOSUPERUSER NOINHERIT  NOCREATEDB  NOCREATEROLE;

CREATE ROLE admin
  NOSUPERUSER INHERIT  CREATEDB  CREATEROLE;

CREATE ROLE diretor LOGIN PASSWORD '1234' 
  SUPERUSER INHERT  CREATEDB CREATEROLE;
GRANT admin TO ditetor;

CREATE ROLE professores LOGIN PASSWORD '1234' 
  NOSUPERUSER NOINHERT  NOCREATEDB NOCREATEROLE;
GRANT geral TO professores;

CREATE SCHEMA s_admin 
  AUTHORIZATION admin; 

CREATE SCHEMA s_geral 
  AUTHORIZATION geral;